name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version twine

      - name: Determine version update
        id: version_update
        run: |
          version_update="patch"
          git log --pretty=format:"%B %an" | while read line; do
            if [[ $line == *"Github Action"* ]]; then
              break
            elif [[ $line == "fix!: "* || $line == "feat!: "* || $line == *"BREAKING CHANGE: "* ]]; then
              version_update="major"
              break
            elif [[ $line == "feat: "* ]]; then
              version_update="minor"
            fi
          done
          echo "::set-output name=version_update::$version_update"

      - name: Bump version and create tag
        run: |
          bump2version ${{ steps.version_update.outputs.version_update }}
          git push && git push --tags

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
